name: Simple Media Downloader

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "youtube / x"
        required: true
        type: choice
        options:
          - youtube
          - x

      url:
        description: "Profile or channel URL"
        required: true

      count:
        description: "How many latest videos?"
        required: false
        default: "5"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: |
          sudo apt update -qq
          sudo apt install -y ffmpeg
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
            -o /usr/local/bin/yt-dlp
          sudo chmod +x /usr/local/bin/yt-dlp

      - name: Download videos
        run: |
          mkdir downloads

          COUNT="${{ github.event.inputs.count }}"
          URL="${{ github.event.inputs.url }}"

          yt-dlp \
            --playlist-end "$COUNT" \
            -o "downloads/%(upload_date)s_%(title)s.%(ext)s" \
            "$URL"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-videos
          path: downloads
